version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            npm install
            ./node_modules/grunt-cli/bin/grunt build
            npm test
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: dev