version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm test
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: dev