version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Before Build
          command: npm install
      - run:
          name: Build
          command: ./node_modules/grunt-cli/bin/grunt build
      - run:
          name: Tests
          command: npm test
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: dev